# Generated by Django 3.2.7 on 2022-03-07 22:30

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default={0: 0, 1: 0, 2: 0}, editable=False),
        ),
        migrations.AddField(
            model_name='hourmodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default={0: 0, 1: 0, 2: 0}, editable=False),
        ),
        migrations.AddField(
            model_name='monthmodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default={0: 0, 1: 0, 2: 0}, editable=False),
        ),
    ]
