# Generated by Django 3.2.7 on 2022-03-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_tag', '0003_auto_20220307_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymodel',
            name='semantic_analysis',
        ),
        migrations.RemoveField(
            model_name='hourmodel',
            name='semantic_analysis',
        ),
        migrations.RemoveField(
            model_name='monthmodel',
            name='semantic_analysis',
        ),
    ]
