# Generated by Django 3.2.7 on 2022-03-07 23:29

import bitcoin_tag.models
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_tag', '0004_auto_20220308_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default=bitcoin_tag.models.default_semantic_analysis_dict, editable=False),
        ),
        migrations.AddField(
            model_name='hourmodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default=bitcoin_tag.models.default_semantic_analysis_dict, editable=False),
        ),
        migrations.AddField(
            model_name='monthmodel',
            name='semantic_analysis',
            field=picklefield.fields.PickledObjectField(default=bitcoin_tag.models.default_semantic_analysis_dict, editable=False),
        ),
    ]
